name: shared_services
services:
  besu:
    image: ghcr.io/velocitynetworkfoundation/blockchain-dev@sha256:596ccbfd5b6153741001428d34946d4294160d323992bd1f05ebdc11953c2fef
    restart: on-failure
    ports:
      - 18545:8545

  localstack:
    image: localstack/localstack@sha256:0bc4495b8a204f80ee16779d968c857f570fd4ea08d3e2e898c226782fe1d74d
    environment:
      - SERVICES=kms,sns,ses,s3
      - PERSISTENCE=1
    volumes:
      - "${LOCALSTACK_VOLUME_DIR:-./localstack.vol}:/var/lib/localstack"
    ports:
      - 14566:4566
      - 14510-14559:4510-4559

  velocity-mongo:
    image: mongo:8.0@sha256:7bd28e5eea1c5766a084d5818254046f3ebe3b8f20a65e3a274640189e296667
    restart: on-failure
    ports:
      - 17017:27017
    volumes:
      - ./mongo-data.vol:/opt/besu/data

  certgen:
    image: alpine/openssl@sha256:f4dead2cc05e01fb683f04ef5573da53ecf2004c8d7603e1c65f6994d8d38313
    restart: on-failure
    volumes:
      - httpscert:/certs
    command: req -x509 -keyout /certs/key.pem -out /certs/cert.crt -sha256 -days 365 -nodes -subj "/CN=e2e-registrar"

  certfix:
    image: alpine@sha256:a8560b36e8b8210634f77d9f7f9efd7ffa463e380b75e2e74aff4511df3ef88c
    restart: on-failure
    volumes:
      - httpscert:/certs
    command: chown -R 1000:1000 /certs
    depends_on:
      - certgen

volumes:
  httpscert: