comment:
  layout: "condensed_header, condensed_files, condensed_footer" # add "condensed_" to "header", "files" and "footer"
  hide_project_coverage: true
coverage:
  status:
    patch:
      default:
        target: 98%
        if_not_found: success
        informational: false
        only_pulls: true
    project:
      default:
        target: auto
        threshold: 0.1%
        removed_code_behavior: adjust_base
        informational: true
        only_pulls: false
