module.exports = (packageName, options = {}) => ({
  roots: ['src', 'test'],
  coverageDirectory: 'coverage/',
  testRegex: '(.*.(test|spec)).(jsx?|tsx?)$',
  moduleFileExtensions: ['ts', 'tsx', 'js', 'jsx', 'json', 'node'],
  collectCoverage: false,
  collectCoverageFrom: [
    '**/src/**/*.{js,jsx}',
    '!**/src/index.js',
    '!**/src/main*.js',
    '!**/coverage/**',
    '!**/test/**',
    '!**/e2e/**',
    '!**/__tests__/**',
    '!**/node_modules/**',
    '!**/migrations/**',
  ],
  coverageReporters: [['lcov', { projectRoot: '../../' }], 'text-summary'],
  verbose: true,
  displayName: packageName,
  reporters: [
    'default',
    [
      'jest-junit',
      {
        outputName: 'test-results.junit.xml',
        outputDirectory: '.',
        ancestorSeparator: ' › ',
        suiteNameTemplate: '{filepath}',
        classNameTemplate: '{classname}',
        titleTemplate: '{title}',
      },
    ],
  ],
  ...options,
});
