services:
  libserver:
    image: nginx:alpine@sha256:6e39bb3765ac959c7e1240509636173417a5e37abf140f418401e2fa73970bbe
    restart: on-failure
    ports:
      - "18082:80"
    volumes:
      - "..:/srv"
      - ./nginx.conf:/etc/nginx/conf.d/default.conf