services:
  libserver:
    image: nginx:alpine@sha256:d67ea0d64d518b1bb04acde3b00f722ac3e9764b3209a9b0a98924ba35e4b779
    restart: on-failure
    ports:
      - "18082:80"
    volumes:
      - "..:/srv"
      - ./nginx.conf:/etc/nginx/conf.d/default.conf