services:
  libserver:
    image: nginx:alpine@sha256:65645c7bb6a0661892a8b03b89d0743208a18dd2f3f17a54ef4b76fb8e2f2a10
    restart: on-failure
    ports:
      - "18082:80"
    volumes:
      - "..:/srv"
      - ./nginx.conf:/etc/nginx/conf.d/default.conf