const SignatoryEventStatus = {
  EMAIL_SENT: 'EMAIL_SENT',
  APPROVED: 'APPROVED',
  COMPLETED: 'COMPLETED',
  REJECTED: 'REJECTED',
  REMINDER_SENT: 'REMINDER_SENT',
  LINK_SENT: 'LINK_SENT',
  REMINDER_ERROR: 'REMINDER_ERROR',
};

module.exports = {
  SignatoryEventStatus,
};
