/**
 * Copyright 2023 Velocity Team
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

/* eslint-disable max-len */
const genericSelfSignedCredential =
  'eyJqd2siOnsia3R5IjoiRUMiLCJleHQiOnRydWUsImtleV9vcHMiOlsidmVyaWZ5Il0sIngiOiI4YWVJVGtaeEpOMFY4UlJTa3NUQlRWeUt3cWlOM1F4QnhudlpGM1h0QkJjIiwieSI6Ikl6ZXJ3eUI0MmZrd25vZEpBRV9lRjVGdnoxeWxYc1lmSXlIRlcydFdXOVUiLCJjcnYiOiJQLTI1NiJ9LCJhbGciOiJFUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJkaWQ6ZXRoci4weGRjZmI1OWUzOThmZWI3YjUxOGY1NmNkY2Q3OThmOWM1NDkzMWZjNzQiLCJ2YyI6eyJAY29udGV4dCI6WyJodHRwczovL3d3dy53My5vcmcvMjAxOC9jcmVkZW50aWFscy92MSJdLCJpZCI6ImRpZDpldGhyLjB4ZGNmYjU5ZTM5OGZlYjdiNTE4ZjU2Y2RjZDc5OGY5YzU0OTMxZmM3NCIsInR5cGUiOlsiSWRlbnRpdHlBbmRDb250YWN0IiwiVmVyaWZpYWJsZUNyZWRlbnRpYWwiXSwiaXNzdWVyIjp7ImlkIjoiZGlkOmV0aHIuMHgwYjE1NGRhNDhkMGYyMTNjMjZjNGIxZDA0MGRjNWZmMWRiZjk5ZmZhIn0sImlzc3VlZCI6IjIwMjAtMDgtMTdUMTE6MjY6MjMuODQwWiIsImNyZWRlbnRpYWxTdWJqZWN0Ijp7ImZpcnN0TmFtZSI6eyJsb2NhbGl6ZWQiOnsiZW4iOiJBZGFtIn19LCJsYXN0TmFtZSI6eyJsb2NhbGl6ZWQiOnsiZW4iOiJTbWl0aCJ9fSwiZW1haWwiOiJhZGFtLnNtaXRoQGV4YW1wbGUuY29tIiwicGhvbmUiOiIrMSA1NTUgNjE5IDIxOTEiLCJkb2IiOnsiZGF5IjozLCJtb250aCI6MywieWVhciI6MTk3MX0sImxvY2F0aW9uIjp7ImNvdW50cnlDb2RlIjoiVVMiLCJyZWdpb25Db2RlIjoiQ0EifSwiaWRlbnRpdHlOdW1iZXIiOnsia2luZCI6IkRyaXZlcnNMaWNlbnNlIiwidmFsdWUiOiIxMjMxMDMxMjMxMiJ9LCJhZGRyZXNzIjp7ImxpbmUxIjoiNDAwIEJlbGwgU3QiLCJsaW5lMiI6IkVhc3QgUGFsbyBBbHRvIiwicG9zdGNvZGUiOiI5NDMwMyIsInJlZ2lvbkNvZGUiOiJDQSIsImNvdW50cnlDb2RlIjoiVVMifX0sImNyZWRlbnRpYWxTdGF0dXMiOnsiaWQiOiJodHRwczovL2NyZWRlbnRpYWxzdGF0dXMudmVsb2NpdHljYXJlZXJsYWJzLmlvIiwidHlwZSI6IlZlbG9jaXR5UmV2b2NhdGlvblJlZ2lzdHJ5In19LCJpc3MiOiJkaWQ6ZXRoci4weDBiMTU0ZGE0OGQwZjIxM2MyNmM0YjFkMDQwZGM1ZmYxZGJmOTlmZmEiLCJpYXQiOjE2MDM3MjUwMTZ9.KFr4naRosxZoEVdbbQsjZkdjQldZRZf0TxmLpxk9Z5-ePZrQhuUftXsuCNZkNV9cEHvzRTdCC1sO__2KqJ2l4A';

const rootIssuerProfileSignedCredential =
  'eyJ0eXAiOiJKV1QiLCJraWQiOiIja2V5LTEiLCJhbGciOiJFUzI1NksifQ.eyJ2YyI6eyJ0eXBlIjpbIk9yZ2FuaXphdGlvbkJhc2ljUHJvZmlsZS12MS4wIiwiVmVyaWZpYWJsZUNyZWRlbnRpYWwiXSwiY3JlZGVudGlhbFN1YmplY3QiOnsibmFtZSI6IlJvb3QgSXNzdWVyIiwibG9nbyI6Imh0dHBzOi8vcm9vdGlzc3Vlci5jb20vbG9nby5wbmciLCJsb2NhdGlvbiI6eyJjb3VudHJ5Q29kZSI6IlVTIiwicmVnaW9uQ29kZSI6IlRYIn0sImZvdW5kZWQiOjIwMDh9fSwiaXNzIjoiZGlkOnZlbG9jaXR5OnJvb3Rpc3N1ZXIxMjM0NTY3ODkwIiwianRpIjoiZGlkOnZlbG9jaXR5OjA0YWViNDJkNzMxMzY1MTc2ZmNjN2U4NDRiZjAxODQzNTc3MjkyYTY1MDM3YWUyYmY5OTNkZDlkZGVhOTZlOTQ3YTUyY2YzNGMwMzNlNjBhYTYzNDQxMzYwMDZlN2EzOTQ4ZDI4Zjk4ODIyOGE0YzlhZGFjMjE0MDJiZWZlOWFlZTgiLCJpYXQiOjE2MjkwNTY3Mzh9.KDot02jYVdSu0FYUEfNloaHipxX6Aqcqs4jXMihzqoc9vhLm12DoAGZohm-_RWHPbfFNv89PP4VM3NKXLZPYnQ';

const sampleOrganizationProfileSignedCredential1 =
  'eyJ0eXAiOiJKV1QiLCJraWQiOiIja2V5LTEiLCJhbGciOiJFUzI1NksifQ.eyJ2YyI6eyJ0eXBlIjpbIk9yZ2FuaXphdGlvbkJhc2ljUHJvZmlsZS12MS4wIiwiVmVyaWZpYWJsZUNyZWRlbnRpYWwiXSwiY3JlZGVudGlhbFN1YmplY3QiOnsibmFtZSI6IkFDTUUgQ29ycCIsImxvZ28iOiJodHRwczovL2V4YW1wbGUuY29tL2xvZ28ucG5nIn19LCJpc3MiOiJkaWQ6dmVsb2NpdHk6cm9vdGlzc3VlcjEyMzQ1Njc4OTAiLCJqdGkiOiJkaWQ6dmVsb2NpdHk6MDRiY2RlNWI0MDExZjU3YjgwZTM5NDY4NjM3MTRlOWI5ZTA1NTdhZDhkYjk5YTAyYzVkYzFkYzBkZTQ2NGEyMTFlMmNkMWFlZjhhY2M2OWE4NWRiYzMyNzVkZDgxZTU5YzA3MDJjYjdkYzU2MmVjYjY1MzVhNGM0MDdlMTIzY2M1MSIsImlhdCI6MTYyOTA4NTI1MH0.vsCbBGkzDQUeFRbTGxtc2JjiVM0Upfe1GGjw1Q-LA8fX3af6O6dwkHWAuAvxipQDrq_fjdBLxVlXrI904P3Wiw';

module.exports = {
  genericSelfSignedCredential,
  rootIssuerProfileSignedCredential,
  sampleOrganizationProfileSignedCredential1,
};
