/**
 * Copyright 2023 Velocity Team
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

/* eslint-disable max-len */
const jwtPublicKey =
  '-----BEGIN PUBLIC KEY-----\nMFkwEwYHKoZIzj0CAQYIKoZIzj0DAQcDQgAE66rlkTzpUlXvBUqxug4lUqSPO0Kr\ni0zggGi71J8hpAlq/Tmh4aATraLEVVEdwQzkCtx4ByKPXZGofc6o8/jOog==\n-----END PUBLIC KEY-----\n';

const jwtTampered =
  'eyJ0eXAiOiJKV1QiLCJraWQiOiIweDExMWM1ZmFlOTc3ZjUyMTY5Yzg3YTA4OTUzMmNkMDQwNDY4YWFlNzkiLCJhbGciOiJFUzI1NiJ9eyJzdWIiOiJkaWQ6dmVsb2NpdHk6MHgxNzJjNWZhZTk3N2Y1MjE2OWM4N2EwODk1MzJjZDA0MDQ2OGFhZTc5IiwidmMiOnsiQGNvbnRleHQiOlsiaHR0cHM6Ly93d3cudzMub3JnLzIwMTgvY3JlZGVudGlhbHMvdjEiXSwiaWQiOiJkaWQ6dmVsb2NpdHk6MHgxNzJjNWZhZTk3N2Y1MjE2OWM4N2EwODk1MzJjZDA0MDQ2OGFhZTc5IiwidHlwZSI6WyJCYWRnZSIsIlZlcmlmaWFibGVDcmVkZW50aWFsIl0sImlzc3VlciI6Iu+/ve+/vWRcdTAwMDBpXHUwMDAwZFx1MDAwMDpcdTAwMDBlXHUwMDAwdFx1MDAwMGhcdTAwMDByXHUwMDAwOlx1MDAwMGlcdTAwMDBhXHUwMDAwbVx1MDAwMGFcdTAwMDBuXHUwMDAwaVx1MDAwMHNcdTAwMDBzXHUwMDAwdVx1MDAwMGVcdTAwMDByXHUwMDAwNVx1MDAwMDVcdTAwMDA1XHUwMDAwNlx1MDAwMDZcdTAwMDA2XHUwMDAwN1x1MDAwMDdcdTAwMDA3XHUwMDAwMFx1MDAwMFxyXHUwMDAwXG5cdTAwMDAiLCJpc3N1YW5jZURhdGUiOiIyMDIwLTA3LTIxVDExOjA0OjEwLjUyMVoiLCJjcmVkZW50aWFsU3ViamVjdCI6eyJob2xkcyI6eyJ0eXBlIjoiQmFkZ2VDbGFzcyIsIm5hbWUiOiJJbmZsdWVuemEgVmFjY2luZSBJbW11bml6YXRpb24gRWR1Y2F0aW9uIChJVklFKSIsImltYWdlIjoiaHR0cDovL2V4YW1wbGUuY29tL2l2aWUucG5nIiwiZGVzY3JpcHRpb24iOiJJbmZsdWVuemEgVmFjY2luZSBJbW11bml6YXRpb24gRWR1Y2F0aW9uIChJVklFKSBpcyBhIHNlbGYtZ3VpZGVkIGxlYXJuaW5nIG1vZHVsZSBmb3IgbnVyc2luZyBzdHVkZW50cyB0byBnYWluIHRyYWluaW5nIHNwZWNpZmljIHRvIHRoZSBhZG1pbmlzdHJhdGlvbiBvZiBpbmZsdWVuemEgdmFjY2luZSBpbiBvcmdhbml6ZWQgY2xpbmljcyBmb3IgY29tbXVuaXRpZXMgb2YgcGVvcGxlIiwiaXNzdWVyIjp7InR5cGUiOiJQcm9maWxlIiwiaWQiOiJkaWQ6dmVsb2NpdHk6ZGVjbGFuaG9zcGl0YWwiLCJuYW1lIjoiRGVjbGFuIEhvc3BpdGFsIn0sImNyaXRlcmlhIjoiaHR0cHM6Ly9leGFtcGxlLmNvbS9pdmllL2NyaXRlcmlhLmh0bWwifX0sImNyZWRlbnRpYWxTdGF0dXMiOnsiaWQiOiJodHRwczovL2NyZWRlbnRpYWxzdGF0dXMudmVsb2NpdHljYXJlZXJsYWJzLmlvIiwidHlwZSI6IlZlbG9jaXR5UmV2b2NhdGlvblJlZ2lzdHJ5In19LCJpYXQiOjE1OTUzMjk0NTB9SEcpMzc+CHQyXBzctm7QlCpOF9qmP0cXMANjZBB4ez5JFw==';

const jwtUntampered =
  'eyJ0eXAiOiJKV1QiLCJraWQiOiIweDM2ZTljNjA2MTg3ODRjYjEyZWRmNzUwMzY5YTIyMGU0MmU0Yzc1MTEiLCJhbGciOiJFUzI1NiJ9.eyJzdWIiOiJkaWQ6dmVsb2NpdHk6MHgzNmU5YzYwNjE4Nzg0Y2IxMmVkZjc1MDM2OWEyMjBlNDJlNGM3NTExIiwidmMiOnsiQGNvbnRleHQiOlsiaHR0cHM6Ly93d3cudzMub3JnLzIwMTgvY3JlZGVudGlhbHMvdjEiXSwiaWQiOiJkaWQ6dmVsb2NpdHk6MHgzNmU5YzYwNjE4Nzg0Y2IxMmVkZjc1MDM2OWEyMjBlNDJlNGM3NTExIiwidHlwZSI6WyJCYWRnZSIsIlZlcmlmaWFibGVDcmVkZW50aWFsIl0sImlzc3VlciI6ImRpZDp2ZWxvY2l0eTppYW1hbmlzc3VlcjU1NTY2Njc3NzAiLCJpc3N1YW5jZURhdGUiOiIyMDIwLTA3LTIxVDEyOjE4OjQ4LjYzOVoiLCJjcmVkZW50aWFsU3ViamVjdCI6eyJob2xkcyI6eyJ0eXBlIjoiQmFkZ2VDbGFzcyIsIm5hbWUiOiJJbmZsdWVuemEgVmFjY2luZSBJbW11bml6YXRpb24gRWR1Y2F0aW9uIChJVklFKSIsImltYWdlIjoiaHR0cDovL2V4YW1wbGUuY29tL2l2aWUucG5nIiwiZGVzY3JpcHRpb24iOiJJbmZsdWVuemEgVmFjY2luZSBJbW11bml6YXRpb24gRWR1Y2F0aW9uIChJVklFKSBpcyBhIHNlbGYtZ3VpZGVkIGxlYXJuaW5nIG1vZHVsZSBmb3IgbnVyc2luZyBzdHVkZW50cyB0byBnYWluIHRyYWluaW5nIHNwZWNpZmljIHRvIHRoZSBhZG1pbmlzdHJhdGlvbiBvZiBpbmZsdWVuemEgdmFjY2luZSBpbiBvcmdhbml6ZWQgY2xpbmljcyBmb3IgY29tbXVuaXRpZXMgb2YgcGVvcGxlIiwiaXNzdWVyIjp7InR5cGUiOiJQcm9maWxlIiwiaWQiOiJkaWQ6dmVsb2NpdHk6ZGVjbGFuaG9zcGl0YWwiLCJuYW1lIjoiRGVjbGFuIEhvc3BpdGFsIn0sImNyaXRlcmlhIjoiaHR0cHM6Ly9leGFtcGxlLmNvbS9pdmllL2NyaXRlcmlhLmh0bWwifX0sImNyZWRlbnRpYWxTdGF0dXMiOnsiaWQiOiJodHRwczovL2NyZWRlbnRpYWxzdGF0dXMudmVsb2NpdHljYXJlZXJsYWJzLmlvIiwidHlwZSI6IlZlbG9jaXR5UmV2b2NhdGlvblJlZ2lzdHJ5In19LCJpYXQiOjE1OTUzMzM5Mjh9.L-jOqtpCa050qEkJn3gVsDrbFgBQwhpl8zVyRGuIdGuOo8XrT1RVSowz29GQHGBIHpVa88Xh7l6HR2Kf_tsjyg';

module.exports = {
  jwtPublicKey,
  jwtTampered,
  jwtUntampered,
};
