FROM node:22.15.1-slim@sha256:ec318fe0dc46b56bcc1ca42a202738aeb4f3e347a7b4dd9f9f1df12ea7aa385a as builder
ARG NODE_ENV=production
ARG SERVICE
ARG SRC_DIR=servers/$SERVICE
WORKDIR /app
RUN chown -R node:node /app

USER root

RUN apt-get update \
  && apt-get install -y --no-install-recommends  python3 make g++ \
  && ln -sf python3 /usr/bin/python

USER node

COPY --chown=node:node package*.json yarn.lock lerna.json .npmrc ./
COPY --chown=node:node packages ./packages
COPY --chown=node:node $SRC_DIR ./servers/$SERVICE
RUN yarn --pure-lockfile

FROM node:22.15.1-slim@sha256:ec318fe0dc46b56bcc1ca42a202738aeb4f3e347a7b4dd9f9f1df12ea7aa385a
WORKDIR /app
COPY --chown=node:node --from=builder /app .
WORKDIR "/app/servers/$SERVICE"

EXPOSE 3000
ENTRYPOINT ["yarn", "start"]
