FROM node:22.17.0-slim@sha256:b04ce4ae4e95b522112c2e5c52f781471a5cbc3b594527bcddedee9bc48c03a0 AS builder
ARG NODE_ENV=production
ARG SERVICE
WORKDIR /app
RUN chown -R node:node /app

USER root

RUN apt-get update \
  && apt-get install -y --no-install-recommends  python3 make g++ \
  && ln -sf python3 /usr/bin/python

USER node

COPY --chown=node:node package*.json yarn.lock lerna.json ./
COPY --chown=node:node packages ./packages
COPY --chown=node:node servers ./servers
RUN yarn --production --pure-lockfile

FROM node:22.17.0-slim@sha256:b04ce4ae4e95b522112c2e5c52f781471a5cbc3b594527bcddedee9bc48c03a0
WORKDIR /app
COPY --chown=node:node --from=builder /app .
WORKDIR "/app/servers/$SERVICE"

EXPOSE 3000
ENTRYPOINT ["yarn", "start"]
