const PurchaseStatus = {
  COUPONS_RECONCILED: 'COUPONS_RECONCILED',
  COUPONS_MINTED: 'COUPONS_MINTED',
  PAYMENT_SUCCEEDED: 'PAYMENT_SUCCEEDED',
  CREDITS_ORDERED: 'CREDITS_ORDERED',
  CREDIT_ORDER_PLACED: 'CREDIT_ORDER_PLACED',
  CREDIT_ORDER_FILLED: 'CREDIT_ORDER_FILLED',
  EXCHANGE_TRANSFER_COMPLETED: 'EXCHANGE_TRANSFER_COMPLETED',
  CASHIER_TRANSFER_COMPLETED: 'CASHIER_TRANSFER_COMPLETED',
  PAYMENT_IN_PROGRESS: 'PAYMENT_IN_PROGRESS',
  PAYMENT_ERROR: 'PAYMENT_ERROR',
  QUOTE_ACCEPTED: 'QUOTE_ACCEPTED',
  PAYMENT_INTENT_CREATED: 'PAYMENT_INTENT_CREATED',
  PAYMENT_INTENT_ERROR: 'PAYMENT_INTENT_ERROR',
  QUOTE_CREATED: 'QUOTE_CREATED',
  INVOICE_VOIDED: 'INVOICE_VOIDED',
  FEES_RECORDED: 'FEES_RECORDED',
};

const PurchaseError = {
  PAYMENT_INSUFFICIENT_FUNDS: 'PAYMENT_INSUFFICIENT_FUNDS',
  PAYMENT_VERIFICATION_ERROR: 'PAYMENT_VERIFICATION_ERROR',
  PAYMENT_OTHER_ERROR: 'PAYMENT_OTHER_ERROR',
  PAYMENT_TIMEOUT: 'PAYMENT_TIMEOUT',
  COUPONS_MINTING_FAILED: 'COUPONS_MINTING_FAILED',
  COUPONS_RECONCILE_FAILED: 'COUPONS_RECONCILE_FAILED',
  CASHIER_TRANSFER_FAILED: 'CASHIER_TRANSFER_FAILED',
  EXCHANGE_TRANSFER_FAILED: 'EXCHANGE_TRANSFER_FAILED',
  CREDITS_ORDER_FAILED: 'CREDITS_ORDER_FAILED',
  CREDITS_ORDER_INSUFFICIENT_LIQUIDITY: 'CREDITS_ORDER_INSUFFICIENT_LIQUIDITY',
};

const CouponStatus = {
  EXPIRED: 'EXPIRED',
  ACTIVE: 'ACTIVE',
};

const PurchaseErrorMessages = {
  PURCHASE_NOT_FOUND_TEMPLATE: ({ purchaseId }) =>
    `Purchase ${purchaseId} not found`,
  PURCHASE_WITH_QUOTE_ID_NOT_FOUND_TEMPLATE: ({ quoteId }) =>
    `Quote ${quoteId} not found`,
  PURCHASE_WITH_PAYMENT_METHOD_NOT_FOUND: ({ quoteId, paymentMethodId }) =>
    `Can't found payment method ${paymentMethodId} for quote ${quoteId}`,
  QUOTE_HAS_EXPIRED: 'Quote has expired',
  QUOTE_BELOW_MINIMUM_THRESHOLD: 'Quote is below minimum threshold',
  QUOTE_EXCEEDS_MAXIMUM_THRESHOLD: 'Quote is exceeds maximum threshold',
  PAYMENT_METHOD_IS_NOT_SET: 'Payment method is not set',
  PRICE_TOO_LOW: 'The minimum price is 5$',
};

const PurchaseSystems = {
  STRIPE: 'STRIPE',
  FINERACT: 'FINERACT',
  EXCHANGE: 'EXCHANGE',
};

module.exports = {
  PurchaseError,
  PurchaseStatus,
  CouponStatus,
  PurchaseErrorMessages,
  PurchaseSystems,
};
