const DisclosureType = {
  NEW: 'new',
  EXISTING: 'existing',
};

const CREDENTIAL_TYPES = {
  EMAIL: 'EmailV1.0',
  PHONE: 'PhoneV1.0',
  DRIVER_LICENSE: 'DriversLicenseV1.0',
  ID_DOCUMENT: 'IdDocumentV1.0',
  NATIONAL_ID_CARD: 'NationalIdCardV1.0',
  PASSPORT: 'PassportV1.0',
  PROOF_OF_AGE: 'ProofOfAgeV1.0',
  RESIDENT_PERMIT: 'ResidentPermitV1.0',
};
const DEFAULT_ID_DOCUMENT_CREDENTIALS_PATH =
  '$.idDocumentCredentials[*].credentialSubject.identifier';
const idCredentialTypeToPick = {
  [CREDENTIAL_TYPES.EMAIL]: '$.emails',
  [CREDENTIAL_TYPES.PHONE]: '$.phones',
  [CREDENTIAL_TYPES.DRIVER_LICENSE]: DEFAULT_ID_DOCUMENT_CREDENTIALS_PATH,
  [CREDENTIAL_TYPES.ID_DOCUMENT]: DEFAULT_ID_DOCUMENT_CREDENTIALS_PATH,
  [CREDENTIAL_TYPES.NATIONAL_ID_CARD]: DEFAULT_ID_DOCUMENT_CREDENTIALS_PATH,
  [CREDENTIAL_TYPES.PASSPORT]: DEFAULT_ID_DOCUMENT_CREDENTIALS_PATH,
  [CREDENTIAL_TYPES.PROOF_OF_AGE]: DEFAULT_ID_DOCUMENT_CREDENTIALS_PATH,
  [CREDENTIAL_TYPES.RESIDENT_PERMIT]: DEFAULT_ID_DOCUMENT_CREDENTIALS_PATH,
};

module.exports = {
  DisclosureType,
  CREDENTIAL_TYPES,
  idCredentialTypeToPick,
};
