name: Blockchain Contracts Tests
on:
  workflow_dispatch:
  push:
    branches:
      - master
      - staging
      - qa
      - dev
    paths:
      - 'contracts/**'
  pull_request:
    branches:
      - master
      - staging
      - qa
      - dev
    paths:
      - 'contracts/**'
env:
  DOCKER_REG: 'ghcr.io'
  NODE_VERSION: '22'
jobs:
  run-contracts-tests:
    name: Run contracts tests
    runs-on: ubuntu-latest
    strategy:
      matrix:
        contract: ["metadata-registry", "revocation-list", "verification-coupon", "permissions"]
    steps:
      # Checkout Repository
      - name: Checkout Repository
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5
      # Setup Node.js
      - name: Setup Node.js
        uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # v4
        with:
          node-version: ${{ env.NODE_VERSION }}
      - name: Login to GitHub Registry
        uses: docker/login-action@184bdaa0721073962dff0199f1fb9940f07167d1 # v3
        with:
          registry: ${{ env.DOCKER_REG }}
          username: $GITHUB_ACTOR
          password: ${{ secrets.VNF_GITHUB_TOKEN }}
      # Install Dependencies
      - name: Install Dependencies
        run: npm i --legacy-peer-deps
        working-directory: ./contracts/${{ matrix.contract }}
      # Compile Contract
      - name: Compile Contract
        run: npm run build
        working-directory: ./contracts/${{ matrix.contract }}
      # Run Contract tests
      - name: Run Contract tests
        run: npm run test
        working-directory: ./contracts/${{ matrix.contract }}
